import fs from 'fs';
import path from 'path';

const DIST_HTML = path.join(process.cwd(), 'dist', 'index.html');
const OUT_CPP = path.join(process.cwd(), '..', 'firmware', 'main-node', 'dashboard_ui.h');

if (!fs.existsSync(DIST_HTML)) {
  console.error('Error: dist/index.html not found. Did you run `npm run build`?');
  process.exit(1);
}

const htmlContent = fs.readFileSync(DIST_HTML, 'utf8');

const cppHeader = `// Auto-generated by dashboard/build-cpp.js
// Do not edit this file directly. Edit the Vite project in /dashboard instead.

#pragma once
#include <Arduino.h>

static const char DASHBOARD_HTML[] PROGMEM = R"STRIKESENSE_HTML(
${htmlContent}
)STRIKESENSE_HTML";
`;

// Ensure target directory exists
const targetDir = path.dirname(OUT_CPP);
if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

fs.writeFileSync(OUT_CPP, cppHeader, 'utf8');
console.log(`Successfully generated C++ header at ${OUT_CPP}`);
