import fs from 'fs';
import path from 'path';
import zlib from 'zlib';

const DIST_HTML = path.join(process.cwd(), 'dist', 'index.html');
const OUT_CPP = path.join(process.cwd(), '..', 'firmware', 'main-node', 'dashboard_ui.h');

if (!fs.existsSync(DIST_HTML)) {
  console.error('Error: dist/index.html not found. Did you run `npm run build`?');
  process.exit(1);
}

const htmlContent = fs.readFileSync(DIST_HTML, 'utf8');

// The build stamp vite wrote into the document, lifted out so the firmware can
// name the build it is serving over a few dozen bytes of JSON. A phone holding
// a dashboard cached before a flash cannot tell it is stale by looking at
// itself, and on HTTPS re-downloading the whole document to find out is far too
// expensive — see checkFreshness() in dashboard/src/freshness.js.
const buildId = (htmlContent.match(/name="ss-build"\s+content="([^"]*)"/) || [])[1] || '';
if (!buildId) {
  console.error('Error: no <meta name="ss-build"> in dist/index.html — vite did not stamp this build.');
  process.exit(1);
}

// Pre-gzip so the ESP32 serves ~44 KB instead of ~163 KB — big win for slow
// mobile clients on the SoftAP (faster first paint, fewer TCP round-trips).
// Byte length, not String#length: that counts UTF-16 code units, and a page
// full of Thai reports ~10% smaller than the file actually is.
const gzInput = Buffer.from(htmlContent, 'utf8');
const gz = zlib.gzipSync(gzInput, { level: 9 });

// emit as a C byte array, 20 bytes per line for readability
let bytes = '';
for (let i = 0; i < gz.length; i++) {
  bytes += (i % 20 === 0 ? '\n    ' : '') + '0x' + gz[i].toString(16).padStart(2, '0') + ',';
}

const cppHeader = `// Auto-generated by dashboard/build-cpp.js
// Do not edit this file directly. Edit the Vite project in /dashboard instead.
//
// The dashboard is stored gzip-compressed and served with Content-Encoding: gzip.
// Raw size: ${gzInput.length} bytes · gzip: ${gz.length} bytes.

#pragma once
#include <Arduino.h>

#define DASHBOARD_BUILD_ID "${buildId}"

static const unsigned int DASHBOARD_HTML_GZ_LEN = ${gz.length};
static const uint8_t DASHBOARD_HTML_GZ[] PROGMEM = {${bytes}
};
`;

// Ensure target directory exists
const targetDir = path.dirname(OUT_CPP);
if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

fs.writeFileSync(OUT_CPP, cppHeader, 'utf8');
console.log(`Generated ${OUT_CPP}`);
console.log(`  raw ${(htmlContent.length / 1024).toFixed(1)} KB → gzip ${(gz.length / 1024).toFixed(1)} KB`);
