import fs from 'fs';
import path from 'path';
import zlib from 'zlib';

const DIST_HTML = path.join(process.cwd(), 'dist', 'index.html');
const OUT_CPP = path.join(process.cwd(), '..', 'firmware', 'main-node', 'dashboard_ui.h');

if (!fs.existsSync(DIST_HTML)) {
  console.error('Error: dist/index.html not found. Did you run `npm run build`?');
  process.exit(1);
}

const htmlContent = fs.readFileSync(DIST_HTML, 'utf8');

// Pre-gzip so the ESP32 serves ~44 KB instead of ~163 KB — big win for slow
// mobile clients on the SoftAP (faster first paint, fewer TCP round-trips).
const gz = zlib.gzipSync(Buffer.from(htmlContent, 'utf8'), { level: 9 });

// emit as a C byte array, 20 bytes per line for readability
let bytes = '';
for (let i = 0; i < gz.length; i++) {
  bytes += (i % 20 === 0 ? '\n    ' : '') + '0x' + gz[i].toString(16).padStart(2, '0') + ',';
}

const cppHeader = `// Auto-generated by dashboard/build-cpp.js
// Do not edit this file directly. Edit the Vite project in /dashboard instead.
//
// The dashboard is stored gzip-compressed and served with Content-Encoding: gzip.
// Raw size: ${htmlContent.length} bytes · gzip: ${gz.length} bytes.

#pragma once
#include <Arduino.h>

static const unsigned int DASHBOARD_HTML_GZ_LEN = ${gz.length};
static const uint8_t DASHBOARD_HTML_GZ[] PROGMEM = {${bytes}
};
`;

// Ensure target directory exists
const targetDir = path.dirname(OUT_CPP);
if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

fs.writeFileSync(OUT_CPP, cppHeader, 'utf8');
console.log(`Generated ${OUT_CPP}`);
console.log(`  raw ${(htmlContent.length / 1024).toFixed(1)} KB → gzip ${(gz.length / 1024).toFixed(1)} KB`);
